title: Nashville stands with Ukraine
description: Support Ukraine in the ongoing Russian invasion
sitename: NashvilleWithUkraine
# baseurl: '/nashvilleWithukraine'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
